### ISSUE TITLE
 Desafio-04-ignite-solid 

### ISSUE THREAD

**Issue by shadowruge** [Vafernandes/Desafio-04-ignite-solid#1]
um README caia bem, não entendi sua proposta.

**Comment by Vafernandes** [comment]
README adicionado amigo!

**Comment by shadowruge** [comment]
Obrigado pelo fidback, da uma força lá nos meus projetos, seria muito grato.
https://github.com/shadowruge

Macetinho que aprendi =>
 https://github.com/shadowruge.png
